### ISSUE TITLE
Borders only use active color (and the inactive aero effects don't work anymore)

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#130] opened 2024-02-08 01:05 UTC
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/0b13f028-49fd-4015-ad2b-8450f56f3710)
As the title says. I've already tried deleting my old config, restarting my machine and DWM itself and no change, except that it worked once after installing.

**Comment by Maplespe** [comment] 2024-02-08 02:35
Are you using a custom bulr method?
We can't reproduce it.

**Comment by angelbruni** [comment] 2024-02-08 02:47
Using CustomBlur method.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/815ab7c3-ba6a-4cf1-b0cd-ea47f2b465e6)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/ae76a4be-34f0-436e-8b85-42bb5713935d)

**Comment by CallyHam** [comment] 2024-02-08 03:12
this is happening to me too, inactive blend color just doesn't do anything, it's always the active color, doesn't matter what kind of blur i choose

**Comment by Maplespe** [comment] 2024-02-08 08:33
What software do you guys use besides StartIsBack?
We've tested fresh installs of Windows 10 21H2 and 22H2 and neither of them can reproduce the problem.
No issues with StartIsBack + 3rd party themes either.

**Comment by Maplespe** [comment] 2024-02-08 13:27
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14209736/Release_x64.zip)
Please try this version, as I'm not sure then what other software is being used, I can only undo some of the changes first to confirm what's causing it.

**Comment by ALTaleX531** [comment] 2024-02-08 14:00
However this is not good news because it means that some software you have installed broke DwmBlurGlass and we need to know exactly which one. 🤔

**Comment by ALTaleX531** [comment] 2024-02-08 14:07
This is not possible, you may have installed some windhawk mods, or perhaps a udwm patch, or something else, because DwmBlurGlass works normally on a fresh install of Windows.

**Comment by Maplespe** [comment] 2024-02-08 14:36
> Oh nevermind, it seems like it's the caption button restorer mod on windhawk. I restarted DWM and the issue wouldn't happen, then i opened windhawk with the mod enabled and it did break the inactive colors
@angelbruni
But why did it work before?

I can't seem to find this mod, where is it? If you can tell me maybe I can optimize this issue.

**Comment by Maplespe** [comment] 2024-02-08 14:41
Where is this module released?

**Comment by Maplespe** [comment] 2024-02-08 14:45
Previously, we accessed the active state of a window by hard-coding its memory address; in the recent update we switched to using the TreatAsActiveWindow function directly
so this caused this issue.
Before
![224320](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/8d7760de-d725-4801-8916-1f1a4114f44a)
After
![224355](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/8f6ae4dc-875b-4003-90d2-acaade3bae76)

But this reduces maintainability and compatibility, that's why we made the adjustment.

**Comment by ALTaleX531** [comment] 2024-02-08 14:45
Looks like we'll have to emulate TreatAsActiveWindow's behavior in every Windows version from now on, sadly!

**Comment by angelbruni** [comment] 2024-02-08 14:55
I am sorry, I've copied the wrong code. Fixed edited my comment (15 minutes ago).
Unfortunately it has not been released and it's not ours either.
I can give you only part of the mod that does the TreatAsActiveWindow behaviour.
```
bool (*CTopLevelWindow_TreatAsActiveWindow_Original)(void);

bool CTopLevelWindow_TreatAsActiveWindow_Hook(void) {
    return TRUE;
}

BOOL Wh_ModInit(void) {
    HMODULE uDWM = GetModuleHandle(L"uDWM.dll");
    if (!uDWM)
        return FALSE;

    WH_FIND_SYMBOL findSymbol;
    HANDLE findSymbolHandle = Wh_FindFirstSymbol(uDWM, nullptr, &findSymbol);
    if (!findSymbolHandle) {
        Wh_Log(L"Wh_FindFirstSymbol failed");
        return FALSE;
    }

    void* TreatAsActiveWindowAddr = nullptr;

    do {
        if (_wcsicmp(findSymbol.symbol,
                     L"private: bool __cdecl "
                     L"CTopLevelWindow::TreatAsActiveWindow(void)") == 0) {
            TreatAsActiveWindowAddr = findSymbol.address;
            Wh_Log(L"symbol: %s, Addr: %i", findSymbol.symbol,
                   findSymbol.address);
        }
    } while (Wh_FindNextSymbol(findSymbolHandle, &findSymbol));

    Wh_SetFunctionHook(TreatAsActiveWindowAddr,
                       (void*)CTopLevelWindow_TreatAsActiveWindow_Hook,
                       (void**)&CTopLevelWindow_TreatAsActiveWindow_Original);
    return TRUE;
}
```
TreatAsActiveWindow is a behaviour in every Windows version from now on, but is there an alternative to disable the fading? Maybe finding the value that sets the opacity/alpha?

**Comment by Maplespe** [comment] 2024-02-08 15:01
Did @dulappy write this?

**Comment by angelbruni** [comment] 2024-02-08 15:03
Yes. This a small portion of the pre-pre-pre-pre-pre-alpha of the final code (which is probably very different and that we don't have access to), so it is doomed to break soon (like it's starting right now with the usage of DWMBlurGlass).

**Comment by windowsxp3790** [comment] 2024-02-08 15:03
> Did @Dulappy write this?

Yes

**Comment by ALTaleX531** [comment] 2024-02-08 15:05
I think it's possible to patch the CTopLevelWindow::UpdateButtonVisuals call to CTopLevelWindow::TreatAsActiveWindow, and modifying the offset corresponding to 0xE8 should work.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/47f29b02-ef6a-4161-b6ea-2c008dc2e5da)
Here's a sample code.
```cpp
class TrampolinePool
{
public:
	UCHAR* Allocate(PVOID detourFunction)
	{
		if (!m_buffer)
		{
			return nullptr;
		}
#ifdef _WIN64
		UCHAR jmpCode[14]{ 0xFF, 0x25 };
		memcpy_s(&jmpCode[6], sizeof(PVOID), &detourFunction, sizeof(detourFunction));
#else
		UCHAR jmpCode[]{ 0xB8, 0, 0, 0, 0, 0xFF, 0xE0, 0 };
		memcpy_s(&jmpCode[1], sizeof(PVOID), &detourFunction, sizeof(detourFunction));
#endif
		if (m_current + sizeof(jmpCode) > m_end)
		{
			return nullptr;
		}

		auto startPos{ m_current };
		memcpy(startPos, jmpCode, sizeof(jmpCode));
		m_current += sizeof(jmpCode);

		return startPos;
	}
	TrampolinePool(PVOID startAddress)
	{
		m_buffer.reset(
			static_cast<UCHAR*>(DetourAllocateRegionWithinJumpBounds(startAddress, &m_bufferSize))
		);

		m_current = m_buffer.get();
		m_end = m_current + m_bufferSize;
	}
	~TrampolinePool() = default;
private:
	DWORD m_bufferSize{0};
	wil::unique_virtualalloc_ptr<UCHAR> m_buffer{ nullptr };
	UCHAR* m_current{ nullptr }, * m_end{ nullptr };
};
LONG ReplaceE8Call(LONG* callOffset, PVOID trampolineAddress)
{
    auto callBaseAddress{ reinterpret_cast<UCHAR*>(reinterpret_cast<DWORD64>(callOffset) + sizeof(LONG)) };
    auto originalOffset{ *callOffset };
    HookHelper::WriteMemory(callOffset, [&]
    {
    	*callOffset = static_cast<LONG>(reinterpret_cast<UCHAR*>(trampolineAddress) - callBaseAddress);
    });
    return originalOffset;
}
```

**Comment by angelbruni** [comment] 2024-02-08 15:06
Good luck with getting it to work! I was simply inspecting the code, unfortunately, I have no coding expertise but thought I should help in any way I can.

**Comment by Xdmg01** [comment] 2024-02-08 21:56
There is also CButton::UpdateCurrentGlyphOpacity
![Screenshot_20240208_224213](https://github.com/Maplespe/DWMBlurGlass/assets/24902344/e7d24c5a-71e9-4d97-8e07-ea0146c2feaa)

This simple Windhawk mod always sets the glyph opacity to 1, tested on windows 21H2 LTSC

```
// ==WindhawkMod==
// @id              inactive-button-opacity
// @name            Inactive Button Opacity
// @version         0.1
// @include         dwm.exe
// ==/WindhawkMod==

#include <windhawk_utils.h>

bool (__thiscall *CButton__UpdateCurrentGlyphOpacity_orig)(void *, bool);
bool __thiscall CButton__UpdateCurrentGlyphOpacity_hook(void *pThis, bool param_1) {
    *((float *)pThis + 101) = 1.0;
    return CButton__UpdateCurrentGlyphOpacity_orig(pThis, param_1);
}

BOOL Wh_ModInit() {
    Wh_Log(L"Init");

    HMODULE uDWM = LoadLibraryW(L"uDWM.dll");

    if (!uDWM) {
        Wh_Log(L"Failed to load uDWM.dll");
        return FALSE;
    }

    WindhawkUtils::SYMBOL_HOOK symbolHook[] = {
        {
            {L"private: void __cdecl CButton::UpdateCurrentGlyphOpacity(bool)"},
            (void**)&CButton__UpdateCurrentGlyphOpacity_orig,
            (void*)CButton__UpdateCurrentGlyphOpacity_hook,
        },
    };

    if (!WindhawkUtils::HookSymbols(uDWM, symbolHook, 1)) {
        Wh_Log(L"Error hooking");
        return FALSE;
    }
    return TRUE;
}
```

**Comment by Maplespe** [comment] 2024-02-10 02:44
Now that you have a solution, I will close it.

**Closed by Maplespe** 2024-02-10 02:44 UTC
Labels: third-party
