### ISSUE TITLE
Taskbar aero reflections?

### ISSUE THREAD

**Issue by TheRealRysieQu** [Maplespe/DWMBlurGlass#206] opened 2024-03-03 21:17 UTC
I would love to see aero reflections on the taskbar and possibly other elements such as windows 7 sidebar gadget. It would add more accuracy if you're trying to do a windows 7 theme on windows 10.

**Comment by TheInsane101** [comment] 2024-03-06 11:11
Duplicate of #105

**Closed** 2024-03-07 06:02 UTC
Labels: duplicate, enhancement
