### ISSUE TITLE
Stops working after a few minutes

### ISSUE THREAD

**Issue by Gurrrra** [Maplespe/DWMBlurGlass#67] opened 2024-01-29 22:47 UTC
I recently installed DWMBlurGlass mostly because this is the only way I've found to change the blur radius of all the existing acrylic stuff in Win10, but it only seem to hold the settings for a few minutes before it just reverts back to default. Then I have to press uninstall and then install again to make it work again for another few minutes.
I'm also running SecureUxTheme, not sure if that might be incompatible with this tool?

**Comment by yuri980** [comment] 2024-01-30 04:01
you can try this- https://windhawk.net/mods/acrylic-effect-radius-changer

**Comment by craftnut** [comment] 2024-02-01 01:17
DWMBlurGlass gets (falsely) marked by Windows Defender as dangerous, have you made an exception for the executable?

**Comment by Maplespe** [comment] 2024-02-01 01:44
@craftnut 
It is well known that most of the beautification software is falsely reported, obviously due to the lack of security certificates issued by Microsoft, and memory modification operations of system processes.
You can do an experiment by writing a small program that will be marked as dangerous as long as the code contains operations such as injecting processes and memory modifications.
This problem cannot be solved, and it is obvious that Microsoft cannot allow these operations.

**Comment by craftnut** [comment] 2024-02-01 02:28
@Maplespe 
I'm aware, just thought that sounds like it could be the issue that Gurrra is having. 
I did not mean to imply it is an issue with the software, sorry

**Comment by Maplespe** [comment] 2024-02-01 02:35
It may be improved in the new version, I think it should fail due to a dwm crash.

**Comment by Maplespe** [comment] 2024-02-01 02:37
I think this should be a problem due to dwm crashes. The new version should improve it though, the crash is caused by DWM Blur internally .

**Comment by Gurrrra** [comment] 2024-02-01 13:01
Yes I have been running the latest version for a couple of hours now and it seems to be stable, thanks @Maplespe !

**Comment by TheInsane101** [comment] 2024-02-03 17:38
@Maplespe so far the 1.0.4 update seems MUCH more stable, which is extremely impressive! How did you do it? Is it still the same type of blur being used, or did you change the type?

**Comment by perfstr54** [comment] 2024-02-04 15:19
There is a problem with displaying folder settings. The same problem is observed on previous versions
![Parameter](https://github.com/Maplespe/DWMBlurGlass/assets/158833519/8db8097a-84f5-4768-9436-25ef38ed368b)

**Closed** 2024-02-06 06:09 UTC
Labels: dwm internal blur
