### ISSUE TITLE
Silent Intsall Parameter

### ISSUE THREAD

**Issue by oxy2ray** [Maplespe/DWMBlurGlass#82] opened 2024-02-03 05:25 UTC
Will this program support silent install? I tried integrating it with my os image, but it doesn't seem to support the silent install parameter.

**Comment by ALTaleX531** [comment] 2024-02-03 05:28
Duplicate of #24.

**Comment by oxy2ray** [comment] 2024-02-03 06:29
closed

**Closed** 2024-02-03 06:29 UTC
Labels: duplicate

**Comment by teknixstuff** [comment] 2024-03-12 20:32
@oxy2ray You can easily silent install it. Just create a scheduled task to run `DWMBlurGlass.exe loaddll` as admin during login.
