### ISSUE TITLE
[Win7 Titlebar Buttons] Fix caption icon/text indent

### ISSUE THREAD

**Issue by aubymori** [Maplespe/DWMBlurGlass#288] opened 2024-04-27 15:00 UTC
**Describe the solution you'd like**
I want for the caption icon and text to not be indented when the option for Windows 7 titlebar buttons is enabbled.

**Your reason (tell us why we need it)**
Windows 7 did not have this; Here's Windows 7, and then Windows 10 with DWMBlurGlass
![image](https://github.com/Maplespe/DWMBlurGlass/assets/44238627/c06d1590-8667-42d3-a2b7-8fc8c8e6b277)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/44238627/a60831b5-9d30-4657-bce1-a98493f42597)

**Describe alternatives you've considered**
There are other solutions to this, but it would be nice to integrate into DWMBG to make it easier for users to make their system look like Windows 7.

**Comment by Maplespe** [comment] 2024-04-27 15:08
Duplicate of #198

**Closed by Maplespe** 2024-04-27 15:08 UTC
Labels: duplicate, enhancement
