### ISSUE TITLE
Blur effect doesn't show when windows in the edge of the screen

### ISSUE THREAD

**Issue by flben233** [Maplespe/DWMBlurGlass#61] opened 2024-01-27 06:50 UTC
I have 2 screens, one of them is 1080p and the other is 3200*2000. The effect only shows rightly in the high resolution one so you can see the background is clear in the first picture.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/40626158/5d56f138-62c0-4057-bda4-e9ec724e997a)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/40626158/b5fef10c-acc0-4048-bd64-456e3d5284bd)

**Comment by Gurrrra** [comment] 2024-01-28 12:38
Just came in here to post the same bug, but mostly bothers me with the taskbar.
![prusa-slicer_240128-133537](https://github.com/Maplespe/DWMBlurGlass/assets/102324673/15361dc4-7691-4d85-b373-240aea0fc660)

**Comment by nopahc4** [comment] 2024-01-28 16:00
that's probably an explorerblur thing,  becomes seethrough when there's a maximized app below

**Comment by flben233** [comment] 2024-01-28 16:52
> that's probably an explorerblur thing, becomes seethrough when there's a maximized app below

I guess the reason is that the implement of the blur effect is like the blur backdrop filter in css.

**Comment by Gurrrra** [comment] 2024-01-28 17:04
> that's probably an explorerblur thing, becomes seethrough when there's a maximized app below
Ah yeah it is. So it's kind of working as intended / unfixable?
![prusa-slicer_240128-180132](https://github.com/Maplespe/DWMBlurGlass/assets/102324673/a2e56bd7-f28b-4e97-b1d1-420045f5df3e)

**Comment by Maplespe** [comment] 2024-02-06 06:10
Resolved in the new version.

**Closed by Maplespe** 2024-02-06 06:10 UTC
Labels: dwm internal blur
