### ISSUE TITLE
Title bar text glow

### ISSUE THREAD

**Issue by quanvinh** [Maplespe/DWMBlurGlass#387] opened 2024-08-30 14:21 UTC
**Describe the solution you'd like**
> For Windows 7 Aero Theme, there was a glow for titlebar's text to help with low contrast of dark/black text on a transparent titlebar on a dark background. I would like to know if it's possible to implement the same thing in DWMBlurGlass.

**Your reason (tell us why we need it)**
> With glow on titlebar, the text is easy to see regardless of what is behind the titlebar:
![gt6q9-1](https://github.com/user-attachments/assets/8399b26c-9282-4597-8032-2fe2e40f15ea)

> Against a dark background with low luminosity set for titlebar, not only the text but even the icons are harder to read due to low contrast:
![image](https://github.com/user-attachments/assets/a857aea8-e390-4d19-bee8-00e6a7c0ee36)

**Describe alternatives you've considered**
> Increasing luminosity would certainly help, but it limits the amount of customisations which are the strong points of DWMBlurGlass.

**Additional context**
> It's hard to see for Acrylic (above screenshot) and even worse for Blur only:
![image](https://github.com/user-attachments/assets/2c74f639-98d6-45b1-bb40-dcb793d49794)

**Comment by SandTechStuff** [comment] 2024-08-30 15:17
DWMBG on Windows 10 has support for text glow when using custom msstyles themes, it would be cool to see something similar for Windows 11.

**Comment by Maplespe** [comment] 2024-09-17 16:42
Duplicate of #215.

**Closed by Maplespe** 2024-09-17 16:42 UTC
Labels: duplicate, enhancement
