### ISSUE TITLE
Logging out and back in requires reinstallation of DWMBlurGlass

### ISSUE THREAD

**Issue by SKCro** [Maplespe/DWMBlurGlass#217] opened 2024-03-16 22:43 UTC
**Describe the bug**
> A clear and concise description of what the bug is:

Whenever I log off and back on, I have to uninstall and reinstall DWMBlurGlass to get the effect to work. I have tried making a scheduled task to launch the program at every login, but it doesn't seem to work and I end up having to open the program and manually uninstall/reinstall.

**To Reproduce**
> Steps to reproduce the behavior:

1) Install DWMBlurGlass
2) Log off and log back in
3) The effect is gone

**Screenshots**
> If applicable, add screenshots to help explain your problem:

Not sure how I'd screenshot or screen-record this, since it involves logging out (which quits capture software).

**Additional information (please complete the following information):**
OS Version: Windows 10 21H2 - IoT LTSC 2021 - Build 19044.4046
Software Version: 2.0.0 (although I don't think 2.0.1 fixes this problem)

**What other third-party software do you use:**
[ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica) and [TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts) (neither of which are causing the problem - disabling and uninstalling them doesn't affect DWMBlurGlass)

**Additional context**
I am using DWMBlurGlass on a portable computer, but that shouldn't affect anything - it doesn't disable transparency when running on battery. I also have the program located in a folder on the root of my drive (`C:\ModernAero\`), so there's that too.

**Comment by Maplespe** [comment] 2024-03-17 01:12
Duplicate of #149.

**Closed by Maplespe** 2024-03-17 01:12 UTC
Labels: question
