### ISSUE TITLE
StartisBack no longer compatible with Aero reflections

### ISSUE THREAD

**Issue by emeraldongithub** [Maplespe/DWMBlurGlass#122] opened 2024-02-07 10:53 UTC
![image](https://github.com/Maplespe/DWMBlurGlass/assets/99167692/31f8e2f9-f506-447e-9b99-db446f8c55c4)

**Comment by ALTaleX531** [comment] 2024-02-07 10:59
Duplicate of #105

**Comment by windowsxp3790** [comment] 2024-02-07 15:23
Is there any plans on trying to replicate/get this effect back?

**Comment by Maplespe** [comment] 2024-02-07 15:34
@windowsxp3790  I think it's explained pretty clearly in #105.

**Closed** 2024-02-09 12:39 UTC
Labels: duplicate
