### ISSUE TITLE
add set blend color from accent color

### ISSUE THREAD

**Issue by alexplaygithub** [Maplespe/DWMBlurGlass#123] opened 2024-02-07 11:36 UTC
hi can you set the feature that sets the blend color to the accent color
but i want to be automatic, because im going to use it in my windows 7 mod, thank you!

![image](https://github.com/Maplespe/DWMBlurGlass/assets/76817483/807adb88-611f-4b15-b7e8-51605d7f5fde)

**Comment by Maplespe** [comment] 2024-02-07 12:13
Duplicate of #86.

**Closed** 2024-02-09 12:39 UTC
Labels: duplicate
