### ISSUE TITLE
DWMBlurGlass CustomBlur crashes on Windows 11 24H2 with Exception code: 0xc0000005

### ISSUE THREAD

**Issue by ImSwordQueen** [Maplespe/DWMBlurGlass#253] opened 2024-04-07 14:00 UTC
**Describe the bug**
Almost all options related to CustomBlur and all the effect settings that would affect Windows 11 now would crash DWM with Exception code: 0xc0000005 if applied on Windows 11 LTSC 2024 Version 24H2 build 26100.1

> Faulting application name: dwm.exe, version: 10.0.26100.1, time stamp: 0xd6fcdd66
> Faulting module name: udwm.dll, version: 10.0.26100.1, time stamp: 0x0a3b97c0
> Exception code: 0xc0000005
> Fault offset: 0x0000000000024187
> Faulting process id: 0x23A8
> Faulting application start time: 0x1DA88F0D967CC63
> Faulting application path: C:\Windows\system32\dwm.exe
> Faulting module path: C:\Windows\SYSTEM32\udwm.dll
> Report Id: 457a70d5-6aa4-4f2d-b88a-c04555ace1e4
> Faulting package full name: 
> Faulting package-relative application ID: 

**To Reproduce**
1. Install DWMGlassBlur on LTSC 2024 [The download for it can be found here](https://archive.org/details/26100-ltsc-x64-enus)
2. If it's not enable, enable customblur.
3. DWM should freeze and crash.

**Screenshots**
![Image](https://github.com/Maplespe/DWMBlurGlass/assets/52015098/4fee48b0-0ff3-4daa-a5f6-08fa80c70aaf)
(Options that would crash DWM no matter what transparency rendering you use)

**Additional information (please complete the following information):**
 > OS Version : Windows 11 LTSC Version 24H2 Build 26100.1
 > Software Version : 2.1.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Startallback 3.7.8 (The crash would still occur without it)
ExplorerPatcher (The crash would still occur without it)

**Additional context**
OldBlur and DWMAPI options do not crash DWM.

**Comment by Maplespe** [comment] 2024-04-07 15:48
Duplicate of #117.
As we noted in ReadMe:
> Compatibility
> Supported as low as Windows 10 2004 and as high as the latest version of Windows 11 (**Some blurring methods are not supported in the preview version**).

**Closed by Maplespe** 2024-04-07 15:48 UTC
Labels: question

**Comment by DanTheGuy720** [comment] 2024-09-20 16:02
Did MS change how DWM works in the latest update again? I thought I remembered reading DWMBlurGlass was more future-proof than previous DWM customizers. Or is that only with cumulative updates?
