### ISSUE TITLE
DWMBlurGlass doesn't run after starting PC.

### ISSUE THREAD

**Issue by daveo76** [Maplespe/DWMBlurGlass#187] opened 2024-02-18 09:32 UTC
**Describe the bug**
DWMBlurGlass won't start. After starting my PC

Description ....
When I start my PC. I have to run it. Click on uninstall. Then click on install. To make it run again. I don't have any themes and UX installed. Apart from those 2 programs I mentioned below. Which is nothing to do with themes
**Additional information (please complete the following information):**
 > OS Version : [Windows 11 23H2.22631.3155]
 > Software Version : [2.0.1]

**What other third-party software do you use:**
TranslucentTB
https://apps.microsoft.com/detail/9PF4KZ2VN4W9?hl=en-us&gl=US
ExplorerPatcher
https://github.com/valinet/ExplorerPatcher

**Comment by Maplespe** [comment] 2024-02-19 06:15
Duplicate of #149.

**Closed by Maplespe** 2024-02-19 06:15 UTC
Labels: duplicate, question
