### ISSUE TITLE
White shadowing for the text in window header

### ISSUE THREAD

**Issue by LavaCreeperYT** [Maplespe/DWMBlurGlass#411] opened 2024-11-14 23:24 UTC
**Solution**
Devs should add a white shadowing to the text in window header like it was in Windows 7

**Reason**
If the window is put on top of something dark the header becomes unreadable - black font on top of the dark background.

**Alternatives**
You can use WindowBlinds with 7 theme to get the shadowing (tho windowblinds is bulky and unstable)

**Additional context**
An example of the shadowing in Windows 7: 
![crop](https://github.com/user-attachments/assets/e0872c58-c0a7-4ec8-a9cb-a14c63513453)

**Comment by Maplespe** [comment] 2024-11-24 10:49
Duplicate of #215.

**Closed by Maplespe** 2024-11-24 10:49 UTC
Labels: duplicate, enhancement
