### ISSUE TITLE
Extreme Lag Upon Dragging Specific Windows Around

### ISSUE THREAD

**Issue by D-Maxwell** [Maplespe/DWMBlurGlass#34] opened 2024-01-22 22:47 UTC
This piece of software of yours is working wonders, although it seems to have trouble with certain apps. Most handle it just fine, but others, like for instance paint.NET, their window moves quite sluggishly.

https://github.com/Maplespe/DWMBlurGlass/assets/98100481/49448e23-d5b4-45d5-82cf-008e8dedf081

Now I don't think I'll be dragging such kinds of windows around often, at least not with my mouse, but I thought this was worth pointing out, in the hope that it is fixable on one's end, either yours or mine.

**Comment by Maplespe** [comment] 2024-01-23 06:21
Duplicate of #31.

**Closed by Maplespe** 2024-01-23 06:21 UTC
Labels: duplicate
