### ISSUE TITLE
transparrent context menu

### ISSUE THREAD

**Issue by xizha127** [Maplespe/DWMBlurGlass#312] opened 2024-05-06 10:34 UTC
**Describe the bug**
> A clear and concise description of what the bug is:

transparrent context menu with the "override AccentBlur effect"

Description ....

I have AccentColorizer, micaforeveryone (with explorerframe) and explorermica running
System is patched with secureux patcher and rectify11 patches.
Having disabled everything this seems to be a bug with dwmglassblur exclusively. 

**To Reproduce**
> Steps to reproduce the behavior:

Clicking right click once the menu shows as normal, but doing so in succession seems to randomly make it fully transparrent. 

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

![image](https://github.com/Maplespe/DWMBlurGlass/assets/147144945/3484ac73-3dde-45ef-b75d-f8dcb38f029b)

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

I have AccentColorizer, 
micaforeveryone (with explorerframe),
explorermica,
secureux patcher,
rectify11 patches.

**Additional context**

Using nilesoft shell seems to make it happen a lot less frequently, so dunno why.

**Comment by Maplespe** [comment] 2024-05-06 11:57
Duplicate of #285.

**Closed by Maplespe** 2024-05-06 11:57 UTC
Labels: duplicate, question
