### ISSUE TITLE
Feature Request: Aero Reflection image

### ISSUE THREAD

**Issue by TheDolphinSlayer** [Maplespe/DWMBlurGlass#5] opened 2024-01-15 16:50 UTC
In Windows Vista - Windows 7 there was this reflection image across the titlebar that would move when the window was move.

Trying to explain this the best I can, it wasn't a static image, it would move around the title bar like a shine. I'll link a video as an example!

At 6:55

https://youtube.com/watch?v=OCqhFtcr_fs&feature=shared

**Comment by Maplespe** [comment] 2024-01-15 17:54
I know this and I've used glass8, but I think all these things are supposed to be provided by 3rd party themes, and it's true if you use a 3rd party theme you can customize these things. That's why my project is called BlurGlass and not AeroGlass, my intention is not to mimic win7 exactly, so if you need it, use a 3rd party theme Thank you.

**Comment by catneptune** [comment] 2024-01-15 18:05
> I'm aware of this and I've used glass8, but I think all these things are supposed to be provided by third party themes, and I was under the impression that if you use a third party theme you can customize these things. That's why my project is called BlurGlass and not AeroGlass, my intention is not to imitate win7 exactly, so if you need it, try using a 3rd party theme Thank you.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/144282272/debbfa00-a6c5-4465-af1c-95c313582ff4)
using a third party theme the reflection image does not seem to be added, maybe could be a nice feature added

**Comment by Maplespe** [comment] 2024-01-15 18:25
Can you send me the theme file?

**Comment by catneptune** [comment] 2024-01-15 18:38
> Can you send me the theme file?

it's aero10, just a reminder:  reflection classes were removed from msstyles entirely in 8, and that there isnt an in-windows way to do it

**Comment by Maplespe** [comment] 2024-01-15 18:56
That does seem to be the case and I will try to implement this feature.

**Comment by nopahc4** [comment] 2024-01-16 05:42
AFAIK aero glass by big muscle doesn't use this texture from the msstyle, because it even works with stock 10 theme if you enable the reflection in the aero glass gui

**Comment by TheDolphinSlayer** [comment] 2024-01-16 06:31
I'm not familiar with how coding works, and I promise I'm not trying to rush your progress but would it help to look at BorderSkin repo on github? (Not to steal code but to get an idea how it works/reference). Its outdated code by many years so im sure there is better alternative solutions

Ignore the broken transparency, more for the way the reflection map works, godbless youtube's great compression on my videos! 

https://github.com/mohamedkomalo/BorderSkin

https://www.youtube.com/watch?v=ki6pn5WdLlM

**Comment by TheDolphinSlayer** [comment] 2024-01-16 19:25
It works great! But there are a little bit of bugs, thank you for your speed in updating it, I am very much grateful, no rush on this. Just wanted to let you know!! 


https://github.com/Maplespe/DWMBlurGlass/assets/73983610/f94f81c3-29aa-47ab-b017-2885a651ef82

**Comment by Maplespe** [comment] 2024-01-16 20:05
Actually it works fine on my computer, I may need to test it more.

**Comment by TheDolphinSlayer** [comment] 2024-01-17 00:21
> Actually it works fine on my computer, I may need to test it more.

I've been noticing that on multi-monitor, the reflection will disappear completely on the second monitor, like my first monitor it appears fine, but once moved over to the second its gone. Same with the taskbar (Left is my first monitor with working reflection the right is my second)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/73983610/1d29d05b-1189-498c-83c4-d8ff4d4b2a36)

**Comment by Maplespe** [comment] 2024-01-17 06:13
So the problem only occurs with multiple monitors, right?

**Comment by TheDolphinSlayer** [comment] 2024-01-17 08:28
> So the problem only occurs with multiple monitors, right?

I believe so

**Comment by nopahc4** [comment] 2024-01-17 08:44
hey, the new update is great but could you add an option to increase the streaks intensity like glass8 had?

**Comment by Maplespe** [comment] 2024-01-17 08:47
> hey, the new update is great but could you add an option to increase the streaks intensity like glass8 had?

There is an AeroPeek.png file in the data folder that you can replace yourself. After replacing it, you can change something in the GUI and click Save Configuration to refresh it.

**Comment by SamueltheTechn0Kid** [comment] 2024-01-18 16:19
How did you get the normal-sized caption buttons?

**Comment by nopahc4** [comment] 2024-01-18 16:19
> How did you get the normal-sized caption buttons?

uDWM.dll patch

**Comment by SamueltheTechn0Kid** [comment] 2024-01-18 17:42
Strange. That patch doesn't work for me with DWMBlurGlass enabled.

**Comment by blondedradio** [comment] 2024-01-18 20:48
> > How did you get the normal-sized caption buttons?
> 
> uDWM.dll patch

What patch is this?

**Comment by nopahc4** [comment] 2024-01-19 02:16
> > > How did you get the normal-sized caption buttons?
> > 
> > 
> > uDWM.dll patch
> 
> What patch is this?

You may ask in the windhawk discord server, since I quit modding and don't have the patched files anymore

**Comment by nopahc4** [comment] 2024-01-19 02:17
> Strange. That patch doesn't work for me at all.

Apparently microsoft broke it with a new update, it causes dwm to crash and locks you out

**Comment by windowsxp3790** [comment] 2024-01-19 14:26
> > Strange. That patch doesn't work for me at all.
> 
> Apparently microsoft broke it with a new update, it causes dwm to crash and locks you out

yes
in the latest 3803 update (now 3930) they broke the uDWM patch
however you can downgrade a few dwm files to previous versions and it will work

**Comment by Maplespe** [comment] 2024-01-19 17:46
The issue should be fixed, in addition to fixing the text glowing issue. #12 
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13992511/Release_x64.zip)

**Comment by nopahc4** [comment] 2024-01-19 18:55
> @TheDolphinSlayer The issue should be fixed, in addition to fixing the text glowing issue. #12 [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13992511/Release_x64.zip)

the issue is fixed, but the windows are kind of glitchy, for example behind the titlebars it shows a different thing than what is actually behind. (in tool windows btw)

**Comment by nopahc4** [comment] 2024-01-19 18:58
https://cdn.discordapp.com/attachments/999083687775830117/1197978461579513856/chrome_CG2y7zwjFU.png?ex=65bd3b62&is=65aac662&hm=6751f738a9f543bb6e29d33400d917222d6771e4b1571e612f6992f68708e415&

**Comment by nopahc4** [comment] 2024-01-19 18:59
and the paint.net window seems to be losing the blur when its being moved, and sometimes lags when dragging

**Comment by Maplespe** [comment] 2024-01-19 19:03
In fact it's an internal problem with dwm's built-in blur effect and we can't fix it for now. For the reflection effect problem I think it has been solved.

**Comment by nopahc4** [comment] 2024-01-19 19:37
> In fact it's an internal problem with dwm's built-in blur effect and we can't fix it for now. For the reflection effect problem I think it has been solved.

alright

**Comment by Maplespe** [comment] 2024-01-19 20:13
I released a new version and also added an option to lower the button height to get a win7-like button style.

**Comment by SamueltheTechn0Kid** [comment] 2024-01-19 21:12
LET'S GOOOO! Thanks!

**Comment by nopahc4** [comment] 2024-01-19 21:50
> I released a new version and also added an option to lower the button height to get a win7-like button style.

I updated, it's ok but the reflection seems to be cut-off from windows like explorer, discord, it's ok on small ones like the run box 
https://media.discordapp.net/attachments/999083687775830117/1198021671945240726/image.png?ex=65bd63a0&is=65aaeea0&hm=26b9c539a67a94018bd5e8e95fed542ef9cf0a770c407c7b2973abbba49955c5&=&format=webp&quality=lossless&width=950&height=46

**Comment by Maplespe** [comment] 2024-01-19 22:05
Is the window between 2 monitors?

**Comment by nopahc4** [comment] 2024-01-19 22:07
> Is the window between 2 monitors?

no, i'm only on 1 monitor, btw i have replaced the aeropeek picture with a solid pink color, it looks like it's only applied to 1 part of the screen and when the window leaves the area it gets cut off 

https://media.discordapp.net/attachments/999083687775830117/1198025660497662063/explorer_CEPd4IaAC7.gif?ex=65bd6757&is=65aaf257&hm=ee4be7a0bb8c2979d289a3a03b94c6d61143b528cd08c648d7bd6f1e74ee00de&=&width=950&height=69

**Comment by Maplespe** [comment] 2024-01-19 22:14
This is strange, I tested everything in a virtual machine and the bottom image should automatically stretch to full screen.
Are your monitors arranged horizontally from left to right and the left is the primary monitor？

**Comment by nopahc4** [comment] 2024-01-19 22:17
> This is strange, I tested everything in a virtual machine and the bottom image should automatically stretch to full screen. Are your monitors arranged horizontally from left to right and the left is the primary monitor？

i have it like this https://cdn.discordapp.com/attachments/999083687775830117/1198028270969561219/image.png?ex=65bd69c6&is=65aaf4c6&hm=05179cdabcaedcbf46c50e38cfd608a956abc78ba9fd04e514a1a0db9f77674d&

monitor 2 is my main monitor which i use, and monitor 1 is my laptop screen that is always off because i have the option set to display only on second monitor

**Comment by Maplespe** [comment] 2024-01-19 22:24
I seem to have guessed why I didn't detect the enabled status of the monitor, and the program may be treating an unenabled monitor as the active monitor. So if you enable all monitors it may solve the problem.

**Comment by valkalyne** [comment] 2024-01-20 07:29
i'm having this same issue , except that i dont have any other monitors connected to my laptop. the cutoff also appears vertically too
![image](https://github.com/Maplespe/DWMBlurGlass/assets/133736967/4c07dc6d-594d-4c33-86f8-a78888b38448)

**Comment by Maplespe** [comment] 2024-01-20 08:31
@valkalyne @nopahc4 Please go to #18 and download the new attachment, it should be fixed .

**Closed** 2024-01-20 16:26 UTC
Labels: enhancement
