### ISSUE TITLE
Rounded corners don't work anymore as of 2.0.0

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#131] opened 2024-02-08 01:10 UTC
They used to work in 1.0.4 and the configuration mentioned in #99 also used to change the radius. There is a default radius (8px) when you enable the effect to extend into borders, but it seems like that hasn't been working since 2.0.0:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/cc0db5ce-a04b-4d00-810a-08967af1ab04)
I've also tried adding

[config]
extendRound=10

to my config.ini, but it doesn't seem to do anything anymore.

**Comment by Maplespe** [comment] 2024-02-08 02:31
Updated with new attachments, please re-download.
However, #130 cannot be reproduced and therefore cannot be fixed.

**Comment by NotJorrd** [comment] 2024-02-08 18:24
I still get this issue, but my current settings make it hard to notice

**Comment by angelbruni** [comment] 2024-02-11 02:02
I found out what causes the rounded corners mask to stop working.
I've disable any applications/mods that interact with DWM for my testing.

The rounded corner masking seems to be tied to the setting "Decrease titlebar button height (win7 style)", as disabling it makes the masking stop working and enabling it makes it work.

With the setting disabled:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/80d1ccff-de37-4001-9c2e-5e043ada3a8e)

With the setting enabled:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/445511ff-4757-4888-98d2-14cacf21bffb)

Ideally, the masking should either be a separate setting or always be left on with the corner radius as a setting (slider), with 0px being equal to disabled.

**Comment by nabriouso** [comment] 2024-02-11 06:36
Bumping this, exact same thing happens to me too with that option.

**Comment by windowsxp3790** [comment] 2024-02-12 21:39
> any updates on this?

Also wondering this ^

**Comment by windowsxp3790** [comment] 2024-02-13 02:18
Bump

**Comment by Maplespe** [comment] 2024-02-13 03:40
This is a temporary version: [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14255830/Release_x64.zip)

**Comment by windowsxp3790** [comment] 2024-02-15 14:31
> This is a temporary version: [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14255830/Release_x64.zip)

Yes that fixed it
Hopefully it'll be added to 2.0.2 soon along with the inactive color fix

**Comment by windowsxp3790** [comment] 2024-03-16 22:31
> This is a temporary version: [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14255830/Release_x64.zip)

Can you push this to the repo ?

**Comment by jonm58** [comment] 2024-03-16 23:04
> > This is a temporary version: [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14255830/Release_x64.zip)
> 
> Can you push this to the repo ?

this ver 22000 not available

**Comment by ImSwordQueen** [comment] 2024-03-27 20:48
This issue hasn't been resolved in 2.1.0

**Closed** 2024-04-26 17:43 UTC
